baseURL = ""
languageCode = "zh-cn"
theme = "SimpleIntro"
title = "About Sidney Zhang"
publishDir = "public"

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "Liangyi Zhang"
    mainTitle = "Simple-intro"
    mainText = "Just simple intro theme for hugo"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "languages"
        name = "Languages"
        url = "#languages"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"