baseURL = ""
languageCode = "zh-cn"
theme = "ExtendIntro"
title = "Who am I"
publishDir = "public"

[params]
    mainbg = "https://images.unsplash.com/photo-1468276311594-df7cb65d8df6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
    name = "Sidney Zhang"
    mainTitle = "Sidney Zhang"
    mainText = "自认为很萌的透明Data Scientist……"

[menus]
    [[menu.main]]
        identifier = "about"
        pre = ""
        name = "About"
        url = "#about"
        weight = 1
    [[menu.main]]
        identifier = "skills"
        pre = ""
        name = "Skills"
        url = "#skills"
        weight = 4
    [[menu.main]]
        identifier = "languages"
        pre = ""
        name = "Languages"
        url = "#languages"
        weight = 5
    [[menu.main]]
        identifier = "projects"
        pre = ""
        name = "Projects"
        url = "#projects"
        weight = 3
    [[menu.main]]
        identifier = "experiences"
        pre = ""
        name = "Experiences"
        url = "#experiences"
        weight = 2
    [[menu.main]]
        identifier = "blog"
        pre = "<i class='fas fa-home'></i>"
        name = ""
        url = "https://lyzhang.me"
        weight = 6